version: '3'

services:
  elasticsearch: #elasticsearch instance
    container_name: elasticsearch-con
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    volumes: # persist data into the volume
      - esdata:/usr/share/elasticsearch/data
    environment: 
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "http.port=9200"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.publish_host=_local_"      
    ports: 
      - "9300:9300"
      - "9200:9200"
      
  backend-api: #application instance
    container_name: elasticsearch-demo
    build: .
    environment:
      - "EL_HOST=elasticsearch"
    ports:
      - "8081:8080"
      
  frontend: #react application
    container_name: elasticsearch-demo-ui
    build:
      context: ./elastic-search-poc-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
            
volumes:
  esdata: